### ISSUE TITLE
Захардкоженность

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-runner-plugin#10]
**RunnerView**

А откуда взялись эти цифры?)

![Снимок экрана в 2019-11-08 21-08-15](https://user-images.githubusercontent.com/38564412/68500185-0e6d7780-026c-11ea-81e5-500905851100.png)

И здесь какое-то непонятное захардкоженное значение

![Снимок экрана в 2019-11-08 21-19-03](https://user-images.githubusercontent.com/38564412/68500736-76708d80-026d-11ea-8431-eb18142f791d.png)

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
В шкале пока что все равно не совсем понятно, почему именно 50 и 100? Откуда берутся эти цифры?

![Снимок экрана в 2019-11-13 21-08-05](https://user-images.githubusercontent.com/38564412/68791126-b95da700-0659-11ea-8b9a-98010bc706e4.png)
