### ISSUE TITLE
Независимость классов

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-runner-plugin#11]
Думаю, независимость классов лучше в отдельное ишью вынести, часто встречается. 

**TrackView**

У тебя трекер сейчас зависит от бегунков, зачем-то добавляет их, разве это его задача? Он должен только отрисовываться в соответсвии со значениями модели, больше у него никаких задач нет.

![Снимок экрана в 2019-11-13 21-49-10](https://user-images.githubusercontent.com/38564412/68794262-c2517700-065f-11ea-978f-83cbf8cc9148.png)

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
А что сейчас поменялось?) В треке по-прежнему фигурируют раннеры, создаются нотификации об их передвижении (откуда трекер знает, что раннеры двигаются?) И зачем раннеры вообще тут нужны?

![Снимок экрана от 2019-11-18 21-38-01](https://user-images.githubusercontent.com/38564412/69079770-c4df1280-0a4b-11ea-9647-51ff08e701e5.png)

Смотри: у тебя есть трекер, у него есть заполненная часть (прогресс), у которой есть левая и правая границы (если это интервал), либо только правая граница. Трекеру только нужно посчитать эти границы, для них ему требуются коэффициенты из модели. Больше он ничего не делает, он у тебя не интерактивный и ни на какие другие компоненты не влияет. Значит, никакие нотификации ему нет нужды создавать, как мне кажется.

**Comment by MorganaLF** [comment]
**Model**

Здесь, я думаю, опции с полем `runnerNumber` в модели тоже лишние, модель ничего не знает про вью. Лучше сразу из контроллера передавать нужный параметр либо вызывать необходимый метод, который бы менял `firstCurrentValue` либо `secondCurrentValue`.

![Снимок экрана от 2019-11-18 22-08-37](https://user-images.githubusercontent.com/38564412/69082053-66686300-0a50-11ea-86b2-305170fbda82.png)

**Comment by MorganaLF** [comment]
Вот здесь, я думаю, вью занимается не своей задачей: рассчитывает значение для модели. Мне кажется, тут во вью достаточно генерировать событие о том, что бегунок двигается, и какое у него ratio. А модель уже сама посчитает свое value.

![Снимок экрана от 2019-11-24 13-49-32](https://user-images.githubusercontent.com/38564412/69493593-88833a80-0ec1-11ea-86b6-3c86cb4f01f2.png)

**Comment by MorganaLF** [comment]
А модель не может предоставлять эти значения? Чтобы тебе не нужно было производить расчеты со значениями модели во вьюхе.

![Снимок экрана от 2019-11-24 13-54-52](https://user-images.githubusercontent.com/38564412/69493643-1e1eca00-0ec2-11ea-8958-8c13ff5795c6.png)

**Comment by Feinminen** [comment]
> А модель не может предоставлять эти значения? Чтобы тебе не нужно было производить расчеты со значениями модели во вьюхе.

Да, может, конечно. Просто изначально мне казалось, что это лишние данные для модели. Если сейчас менять данные модели, то много какие зависимости менять бы пришлось, поэтому решил рассчитывать их непосредственно в мэйн вью. Если нужно - поменяю)
