### ISSUE TITLE
Сохранение контекста

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-runner-plugin#15]
Есть разные способы сохранения контекста, не обязательно оборачивать метод в стрелочную функцию. Об этом как раз будет вопрос на интервью. Например, можно использовать bind и декораторы, чтобы избежать лишней писанины.

MainView.ts
![Снимок экрана от 2019-11-24 13-47-37](https://user-images.githubusercontent.com/38564412/69493553-01ce5d80-0ec1-11ea-9534-cceea9a62c14.png)

**Comment by Feinminen** [comment]
> Например, можно использовать bind и декораторы, чтобы избежать лишней писанины

Я, честно говоря, наоборот пытался избавляться от 'bind' в проекте. Даже stage-3 proposal специально для этого подключал, ибо там есть возможность методы класса в стрелочные функции загонять, чтобы в конструкторе не использовать bind для обработчиков событий.

**Comment by MorganaLF** [comment]
А почему старался избавиться? Если подключить декораторы, то будет достаточно писать что-то вроде 

```
@bind
someMethosName() {
  ...
}
```

И контекст будет сохранен всегда.

Другой вариант сохранения контекста это свойства классов, в которые можно записать стрелочные функции, этот способ у тебя уже используется:

![Снимок экрана от 2019-11-24 23-18-16](https://user-images.githubusercontent.com/38564412/69500925-c9567000-0f10-11ea-95dd-a37e2c2561da.png)

А обертки из функций, мне кажется, это лишнее
