### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-runner-plugin#16]
Сейчас в проекте ts используется очень поверхностно, у тебя мало что затипизировано. Вот здесь например, непонятно, что можно передать в options:

![Снимок экрана от 2019-11-24 13-57-38](https://user-images.githubusercontent.com/38564412/69493677-91284080-0ec2-11ea-9ac1-9f19c4e1492d.png)

Также не указано, какие методы являются публичными, а какие приватными.

Вот такие моменты предлагаю выносить в интерфейсы и типы, а не писать прямо в методах: 

![Снимок экрана от 2019-11-24 14-00-09](https://user-images.githubusercontent.com/38564412/69493692-d3518200-0ec2-11ea-957e-1fd0da2c4258.png)

**Comment by Feinminen** [comment]
> Также не указано, какие методы являются публичными, а какие приватными.

Есть такое, но у меня с приватными методами возникали проблемы с тестами. Приватные методы лучше вообще не тестировать или это как-то исхищренно делается?

**Comment by MorganaLF** [comment]
> Есть такое, но у меня с приватными методами возникали проблемы с тестами. Приватные методы лучше вообще не тестировать или это как-то исхищренно делается?

А вот эту задачу, по идее, решает TDD) Нет, приватные методы сами по себе не тестируются, тестируются только публичные методы, которые, в свою очередь, их используют. И во время написания тестов у тебя как раз должен был возникнуть вопрос: какие методы твоих классов должны быть публичными и должны быть доступны извне для других классов, а также тестироваться, а какие методы решают исключительно внутренние задачи класса, и о которых не должен больше знать никто.

**Comment by MorganaLF** [comment]
Осталось отсортировать  расположение методов в соответствии со стандартами, пункт 5. 
https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/architecture.md
