### ISSUE TITLE
Убрать явные кастования везде где можно

### ISSUE THREAD

**Issue by Znack** [Feinminen/FSD-runner-plugin#19]
Например в plugin/slider.ts убрать каст в  `new Model(newOptions as StrictOptions)`. Остальные места проекта проверить самому :)

**Comment by Feinminen** [comment]
Хотелось бы уточнить какие касты являются допустимыми.

**Comment by Znack** [comment]
Ну можно делать, когда совсем без этого никак и это явно помогает оставшийся код вокруг более удобным для чтения и редактирования :)

По-хорошему, касты типа результатов `querySelector` делать через narrowing типа — то есть сначала в рантайме прочекать что там действительно нужный тебе тип элемента вернулся и только потом приводить. Вот пример: https://typescript-play.js.org/#code/DYUwLgBCwQvBATA9gYwK4FsQDswDoBHNEAJwE8BlaEFMJEgCgCIBiBEAMwEtsuxoyAQWwBJDAEMA5iCYBKANwAoAPTKIAN3Eku4gEagoMABakQELgGcIYMgAcQCa0ggBRUFlwQAPhGxpgwIpcHBAM0BAAZBGG5tgWYOLYKCBIIQASACoAsgAyYlIgbiAeYLIQAN6KEBCqMSYkZpa+WiRIAO4OThCZufnSRSUQAFyyVYZ4FiQocBBMHEhIeLbYkkxKAL5AA

Прочитай там комменты, наведи на `el` вне проверки и посмотри какой TS тебе покажет тип, и потом внутри тела `if` на ту же `el`, там TS покажет уже другой тип. Можешь на `el` навести даже внутри условия `if` где используется `instanceof`, там будет тип уже без `| null` :)
