### ISSUE TITLE
Не мутировать в геттерах

### ISSUE THREAD

**Issue by Znack** [Feinminen/FSD-runner-plugin#21]
Функции, которые используются для чтения каких либо значений лучше держать без сайд-эффектов — мы не знаем сколько раз и в каких случаях эти функции будут вызываться. Если при каждом вызове мутировать что-то внутри, то можно нарваться на обидные баги, когда внеший код поменяет модель поведения и начнет по другому паттерну вызов геттера делать. Тут можно почитать про CQS :)
В частности нашел это в `getTrack`: `this.track.appendChild(this.progress);`. Может есть ещё места, лучше тебе просмотреть проект

**Comment by Feinminen** [comment]
Внёс правки по всем ишьюс. Почитал про CQS, достаточно интересный принцип! Но что-то мне подсказывает, что идеально его соблюдать будет достаточно проблематично :D В дальнейшем в проектах буду следить, чтобы геттеры не мутировали ничего)
