### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by Frolikow** [Feinminen/FSD-runner-plugin#22]
При данных настройках, неправильно работает слайдер.
![image](https://user-images.githubusercontent.com/25764783/70529710-d1a2e200-1b83-11ea-90e4-fdb8374b7980.png)
Чтобы выбрать значение 500 нужно прилично увести ползунок за слайдер, и где-то там же (вне слайдера) происходит скачек с 500 на 400.

Надо чтобы ползунок менял положение так же, как и в обычных случаях - по середине между соседними значениями.

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/70530000-7ae9d800-1b84-11ea-8664-de9c80fdedf7.png)
С такими параметрами, если кликнуть по шкале - второе значение отваливается

**Comment by Feinminen** [comment]
Внёс все правки. Решил ещё поменять расчёт количества элементов шкалы, т.к. порой не отрисовывалось максимальное значение(изначально это было сделано, чтобы элементы не наезжали друг на друга).

**Comment by Frolikow** [comment]
В целом все хорошо, но одно "но"
сейчас если кликать по шкале то ползунки перемещаются логично и правильно
но если отключить шкалу и кликать по самому слайдеру, то первый ползунок улетает на минимум, а второй стоит на месте
