### ISSUE TITLE
Деструктуризация

### ISSUE THREAD

**Issue by Frolikow** [Feinminen/FSD-runner-plugin#25]
Обратил внимание, что ты в некоторых местах не делаешь деструктуризацию. Например: 
![image](https://user-images.githubusercontent.com/25764783/70601843-9b1da380-1c25-11ea-993e-7530c5f7d46e.png)
а в некоторых делаешь (хоть и переусложненно)
![image](https://user-images.githubusercontent.com/25764783/70601905-c2747080-1c25-11ea-8509-a91b7f8f10b7.png)
при этом ты вроде деструкторировал, а всеравно `this.options.hasInterval` дальше пишешь

**Comment by Frolikow** [comment]
Сразу скажу, при деструктуризации можно легко брать вложенные переменные. Например:
вместо
```js
    const { options } = this;
    const { firstCurrentValue, secondCurrentValue, isVertical, hasInterval, hasTooltip } = options;
    const { firstRatio, secondRatio } = options.ratios;
```
можно писать 
```js
const { firstCurrentValue, 
secondCurrentValue,
isVertical,
hasInterval, 
hasTooltip, 
ratios: { firstRatio, secondRatio } } = this.options;
```
 каждую переменную писать на новой строке - конечно не обязательно, но когда их больше, например, 2-3штук то читать удобнее, когда они в столбец записаны)

**Comment by Feinminen** [comment]
> Сразу скажу, при деструктуризации можно легко брать вложенные переменные.

Да, я не знал, что можно вложенные переменные доставать, хотя это достаточно очевидно 😅

**Comment by Feinminen** [comment]
Я специально не стал деструктурировать объекты, где их свойства только один раз используются, надеюсь это ок.
Внёс правки по всем ишьюс, надеюсь теперь ничего нигде не пропустил)

**Comment by Frolikow** [comment]
> Я специально не стал деструктурировать объекты, где их свойства только один раз используются, надеюсь это ок.

Деструктуризация не только для того чтобы убрать повторяющиеся свойства объекта) еще и для того чтобы внутри одного метода не было постоянных `this.options`, как например было здесь:
![image](https://user-images.githubusercontent.com/25764783/70641105-ac8b9d80-1c6f-11ea-9cfe-f9b61baf4afe.png)

и кстати, в примере, ты и min используешься несколько раз(2) и step тоже(4) и все в одном методе))

**Comment by Feinminen** [comment]
> Я специально не стал деструктурировать объекты, где их свойства только один раз используются, надеюсь это ок.

Тут я про исправления непосредственно в комитете говорил)
До исправлений там действильно было много недочётов с деструктуризацией.
