### ISSUE TITLE
View

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-runner-plugin#4]
У тебя сейчас одна вьюха на всё - и на трекер, и на бегунок, и на шкалу. Гораздо лучше разбить это на отдельные классы, чтобы каждый класс отвечал за что-то одно. Тогда будет и проще поддерживать такой код, и можно будет избавиться от того нагромождения, которое у тебя сейчас есть во вьюхе, заодно и конструктор разгрузить можно будет.

По остальным вещам пока не буду писать замечания, потому что после разбивки на классы скорее всего всё сильно изменится.

![Снимок экрана в 2019-10-04 11-28-54](https://user-images.githubusercontent.com/38564412/66192919-2f094700-e69a-11e9-8b0d-e26f16689aca.png)

**Comment by MorganaLF** [comment]
Мне кажется, пока что не совсем логично получилось. Например: у тебя есть трекер, но он почему-то имеет методы updateTooltips и updateThumbs. Для таких задач нужно использовать подписки и контроллер.
В главной вьюхе осталась работа с thumb, хотя это имеет смысл выделить в отдельный класс, потому что thumb довольно много чем занимается. Аналогично с tooltip.
Думаю, главная вьюха должна быть таким классом, который просто собирает все вьюхи вместе, при необходимости слушает какие-то их события, чтобы дальше передать эти события контроллеру. А в той реализации, что у тебя сейчас, не совсем понятно, почему это MainView, почему это отдельный класс и за что он отвечает.

**Comment by MorganaLF** [comment]
А сейчас у тебя снова та же ошибка, что была на втором проекте - у тебя классы ThumbsView и TooltipsView рисуют по два одинаковых элемента. Зачем им знать, что их два? Это уже дело главной вьюхи, два у нее бегунка или один.А класс как раз и предназначен для того, чтобы можно было создавать сколько угодно одинаковых элементов путем создания инстансов.

**Comment by MorganaLF** [comment]
И еще, смотри, у тебя в главной вьюхе остался метод `handleDocumentMouseMove`. Чей это метод? Ведь самой вьюхе событие mousemove неинтересно, тем более, что тебе нужно слушать  mousemove не абсолютно всегда, а только при определенных условиях.

**Comment by MorganaLF** [comment]
Вот это, мне кажется, лишнее в конструкторе. Может, перенести в init()?

![Снимок экрана в 2019-11-08 20-25-20](https://user-images.githubusercontent.com/38564412/68497601-fdba0300-0265-11ea-883d-85a710610948.png)

**Comment by MorganaLF** [comment]
Demo-page снова в плагине фигурирует. Почему вьюха должна знать, что она создается в '.demo-page__container'? И если мне надо будет на проекте разместить слайдер, мне обязательно надо будет создавать '.demo-page__container'?

![Снимок экрана в 2019-11-08 20-26-23](https://user-images.githubusercontent.com/38564412/68497686-2e9a3800-0266-11ea-9516-6621a0672d13.png)

**Comment by MorganaLF** [comment]
А здесь нельзя сразу инициализировать в конструкторе шкалы? Или там какая-то зависимость есть?

![Снимок экрана в 2019-11-08 20-30-01](https://user-images.githubusercontent.com/38564412/68497878-981a4680-0266-11ea-9773-7470d0726778.png)

**Comment by MorganaLF** [comment]
А slider-runner это что? А то я что-то его не нашла)

![Снимок экрана в 2019-11-08 20-43-39](https://user-images.githubusercontent.com/38564412/68498678-8174ef00-0268-11ea-82de-9aefb16803a8.png)

![Снимок экрана в 2019-11-08 20-44-27](https://user-images.githubusercontent.com/38564412/68498699-92256500-0268-11ea-9736-1b8412a26332.png)

**Comment by MorganaLF** [comment]
**RunnerView**

Здесь у тебя какие-то странные расчеты производятся, вью только рисуется в соответствии с настройками модели, а модель сама считает свои значения. А у тебя почему-то вьюха сама все посчитала, и готовое значение в модель отправила. 

Причем, по идее вью нет разницы, какое там конкретное текущее значение. Может, там от у модели значения от 1000 до 2000, а может, от 0 до 5, а может там вообще рубли или миллиметры. Но это ведь не влияет на положение бегунка, верно? Единственное, что влияет на его положение, это коэффициент.

![Снимок экрана в 2019-11-08 20-57-08](https://user-images.githubusercontent.com/38564412/68499478-58555e00-026a-11ea-92ec-13a270893dfb.png)

Еще непонятно, зачем бегунку знать, первый он или второй, он ведь просто отрисовывается в нужном месте?

![Снимок экрана в 2019-11-08 20-55-30](https://user-images.githubusercontent.com/38564412/68499407-2e9c3700-026a-11ea-8fb0-cdca89eb328f.png)

**Comment by MorganaLF** [comment]
**TrackView**

Вот этот момент не совсем понятен - трекер обновляет настройки бегунков? Зачем? И зачем вообще трекер знает про бегунки?

![Снимок экрана в 2019-11-08 21-24-22](https://user-images.githubusercontent.com/38564412/68501046-39f16180-026e-11ea-95c7-4c9356416ff7.png)

**Comment by Feinminen** [comment]
> **View**
> 
> А здесь нельзя сразу инициализировать в конструкторе шкалы? Или там какая-то зависимость есть?
> 
> ![Снимок экрана в 2019-11-08 20-30-01](https://user-images.githubusercontent.com/38564412/68497878-981a4680-0266-11ea-9773-7470d0726778.png)

Да, там есть одна маленькая зависимость из-за которой пришлось так сделать. Там позиция каждого числа высчитывается, исходя из ширины этого числа(т.к. её сдвигать нужно для точного позиционирования). А если шкала ещё не закинута в DOM, то получается что размеров у элементов нет.  Возможно это не совсем ок, но на тот момент другого решения в голову не пришло.

**Comment by Feinminen** [comment]
> Еще непонятно, зачем бегунку знать, первый он или второй, он ведь просто отрисовывается в нужном месте?
> 
> ![Снимок экрана в 2019-11-08 20-55-30](https://user-images.githubusercontent.com/38564412/68499407-2e9c3700-026a-11ea-8fb0-cdca89eb328f.png)

У меня в модели есть два свойства отвечающие за положение первого и второго бегунка - firstCurrentValue и secondCurrentValue. Т.к. бегунки, как элементы, должны быть абсолютно идентичны, я решил сверху передавать номер бегунка, чтобы знать какое из свойств модели необходимо менять и позицию какого из бегунков менять :)

**Comment by MorganaLF** [comment]
По-прежнему непонятен маневр в MainView: почему бы просто не передать в параметры элемент-контейнер, и сразу к нему всё аппендить, зачем это лишнее действие с вложенной структурой? `this.root.firstChild`

![Снимок экрана в 2019-11-13 21-30-05](https://user-images.githubusercontent.com/38564412/68792725-01ca9400-065d-11ea-92ee-3eafb48ca9b1.png)

**Comment by MorganaLF** [comment]
> У меня в модели есть два свойства отвечающие за положение первого и второго бегунка - firstCurrentValue и secondCurrentValue. Т.к. бегунки, как элементы, должны быть абсолютно идентичны, я решил сверху передавать номер бегунка, чтобы знать какое из свойств модели необходимо менять и позицию какого из бегунков менять :)

Но по идее ведь у тебя только главная вьюха знает, сколько у нее бегунков. А сами бегунки ничего друг про друга не знают, им эта информация ни к чему, их количество никак на них не влияет. Главная вьюха состоит из каких-то частей, значит, она знает про свои части. А вот части сами по себе и не зависимы.

Проведи аналогию с бэм: у тебя компонент может состоять из других компонентов и знать про них. А вот вложенные в него компоненты должны быть независимыми от контекста.

**Comment by MorganaLF** [comment]
Вот здесь в главной вьюхе ты прокинул в трекер `ratio`, и еще `firstCurrentValue` и `secondCurrentValue`, а одного только `ratio` разве не должно быть достаточно? Тебе ведь для того, чтобы установить положение бегунка / трекера, достаточно знать только координаты в документе и `ratio`, для чего понадобились еще  `firstCurrentValue` и `secondCurrentValue`?

![Снимок экрана от 2019-11-24 13-14-27](https://user-images.githubusercontent.com/38564412/69493193-f24d1580-0ebc-11ea-879d-6282ffe0d9ac.png)

**Comment by Feinminen** [comment]
> Вот здесь в главной вьюхе ты прокинул в трекер `ratio`, и еще `firstCurrentValue` и `secondCurrentValue`, а одного только `ratio` разве не должно быть достаточно? Тебе ведь для того, чтобы установить положение бегунка / трекера, достаточно знать только координаты в документе и `ratio`, для чего понадобились еще `firstCurrentValue` и `secondCurrentValue`?

Для того чтобы установить положение самого бегунка - вполне достаточно, а вот чтобы поставить числовое значение тултипа - не совсем. Собственно first/secondCurrentValue там только для того, чтобы подставлять эти данные в тултип :)

**Comment by MorganaLF** [comment]
> Для того чтобы установить положение самого бегунка - вполне достаточно, а вот чтобы поставить числовое значение тултипа - не совсем. Собственно first/secondCurrentValue там только для того, чтобы подставлять эти данные в тултип :)

Да, точно, забыла, что у тебя там еще tooltip)
